### ISSUE TITLE
mini/pages/cssCase/stepsAnt CSS少了flex布局样式

### ISSUE THREAD

**Issue by hrhhz** [susu-hu/susu-mini-tem#3]
mini/pages/cssCase/stepsAnt 页面少了flex布局样式！
本人由于后端，不擅长前端及css，大胆修改一点在改page的css文件中添加
.con-item {
        display: flex;
        flex-direction: row;
        text-align: center;
        justify-content: center;
}

**Comment by susu-hu** [comment]
有公共样式哈，在app.wxss中
